
/* TPC_H Query 1 - */
--  Cold / Hot Cache
-- Native Redshift: 4.36s / 0.8s
-- Spectrum S3 Storage: 20.58s / 12.77s
SELECT L_RETURNFLAG, L_LINESTATUS, SUM(L_QUANTITY) AS SUM_QTY,
 SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS SUM_DISC_PRICE,
 SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)*(1+L_TAX)) AS SUM_CHARGE, AVG(L_QUANTITY) AS AVG_QTY,
 AVG(L_EXTENDEDPRICE) AS AVG_PRICE, AVG(L_DISCOUNT) AS AVG_DISC, COUNT(*) AS COUNT_ORDER
FROM spectrum.LINEITEM
WHERE L_SHIPDATE <= DATE'1998-12-01'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG,L_LINESTATUS

/* TPC_H Query 2 - Minimum Cost Supplier */
-- 16.39s / 1.37s
-- 22.2s /  10.41
with ps as (SELECT MIN(PS_SUPPLYCOST) AS PS_COL FROM spectrum.PARTSUPP, spectrum.SUPPLIER, spectrum.NATION, spectrum.REGION
 WHERE PS_PARTKEY = PS_PARTKEY AND S_SUPPKEY = PS_SUPPKEY
 AND S_NATIONKEY = N_NATIONKEY AND N_REGIONKEY = R_REGIONKEY AND R_NAME = 'EUROPE')

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM spectrum.PART, spectrum.SUPPLIER, spectrum.PARTSUPP, spectrum.NATION, spectrum.REGION, PS
WHERE P_PARTKEY = PS_PARTKEY AND S_SUPPKEY = PS_SUPPKEY AND P_SIZE = 15 AND
P_TYPE LIKE '%%BRASS' AND S_NATIONKEY = N_NATIONKEY AND N_REGIONKEY = R_REGIONKEY AND
R_NAME = 'EUROPE' AND PS_SUPPLYCOST > PS_COL
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY

/* TPC_H Query 3 - Shipping Priority */
-- 7.72s / 2.75s
-- 23.91s / 18.46s
SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM spectrum.CUSTOMER, spectrum.ORDERS, spectrum.LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING' AND C_CUSTKEY = O_CUSTKEY AND L_ORDERKEY = O_ORDERKEY AND
O_ORDERDATE < DATE'1995-03-15' AND L_SHIPDATE > DATE'1995-03-15'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE 


/* TPC_H Query 4 - Order Priority Checking */
-- 8.21s / 0.86s
-- 24.32s / 18.33s
WITH L as (SELECT COUNT(*) as L_COUNT FROM spectrum.LINEITEM, spectrum.ORDERS 
           WHERE L_ORDERKEY = O_ORDERKEY AND L_COMMITDATE < L_RECEIPTDATE)
SELECT O_ORDERPRIORITY, COUNT(*) AS ORDER_COUNT FROM spectrum.ORDERS, L
WHERE O_ORDERDATE >= DATE'1993-07-01' AND O_ORDERDATE < DATE'1993-04-01' AND L_COUNT != 0
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY

/* TPC_H Query 5 - Local Supplier Volume */
-- 9.33s 0.92s
-- 22.21s / 19.27s
SELECT N_NAME, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS REVENUE
FROM spectrum.CUSTOMER, spectrum.ORDERS, spectrum.LINEITEM, spectrum.SUPPLIER, spectrum.NATION, spectrum.REGION
WHERE C_CUSTKEY = O_CUSTKEY AND L_ORDERKEY = O_ORDERKEY AND L_SUPPKEY = S_SUPPKEY
AND C_NATIONKEY = S_NATIONKEY AND S_NATIONKEY = N_NATIONKEY AND N_REGIONKEY = R_REGIONKEY
AND R_NAME = 'ASIA' AND O_ORDERDATE >= DATE'1994-01-01' 
AND O_ORDERDATE < DATE'1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC

/* TPC_H Query 6 - Forecasting Revenue Change */
-- 3.65s / 0.23s
-- 12.21s / 12.85s
SELECT SUM(L_EXTENDEDPRICE*L_DISCOUNT) AS REVENUE
FROM spectrum.LINEITEM
WHERE L_SHIPDATE >= DATE'1994-01-01' AND L_SHIPDATE < DATE'1995-01-01'
AND L_DISCOUNT BETWEEN .06 - 0.01 AND .06 + 0.01 AND L_QUANTITY < 24

/* TPC_H Query 7 - Volume Shipping */
-- Invalid operation: function year(timestamp without time zone)
SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM ( SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, year(L_SHIPDATE) AS L_YEAR,
 L_EXTENDEDPRICE*(1-L_DISCOUNT) AS VOLUME
 FROM spectrum.SUPPLIER, spectrum.LINEITEM, spectrum.ORDERS, spectrum.CUSTOMER, spectrum.NATION N1, spectrum.NATION N2
 WHERE S_SUPPKEY = L_SUPPKEY AND O_ORDERKEY = L_ORDERKEY AND C_CUSTKEY = O_CUSTKEY
 AND S_NATIONKEY = N1.N_NATIONKEY AND C_NATIONKEY = N2.N_NATIONKEY AND  ((N1.N_NAME = 'FRANCE' AND N2.N_NAME = 'GERMANY') OR
 (N1.N_NAME = 'GERMANY' AND N2.N_NAME = 'FRANCE')) AND
 L_SHIPDATE BETWEEN DATE'1995-01-01' AND DATE'1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR


/* TPC_H Query 8 - National Market Share */
-- Invalid operation: function year(timestamp without time zone) does not exist;
SELECT O_YEAR, SUM(CASE WHEN NATION = 'BRAZIL' THEN VOLUME ELSE 0 END)/SUM(VOLUME) AS MKT_SHARE
FROM (SELECT year(O_ORDERDATE) AS O_YEAR, L_EXTENDEDPRICE*(1-L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
 FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
 WHERE P_PARTKEY = L_PARTKEY AND S_SUPPKEY = L_SUPPKEY AND L_ORDERKEY = O_ORDERKEY
 AND O_CUSTKEY = C_CUSTKEY AND C_NATIONKEY = N1.N_NATIONKEY AND
 N1.N_REGIONKEY = R_REGIONKEY AND R_NAME = 'AMERICA' AND S_NATIONKEY = N2.N_NATIONKEY
 AND O_ORDERDATE BETWEEN DATE'1995-01-01' AND DATE'1996-12-31' AND P_TYPE= 'ECONOMY ANODIZED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR

/* TPC_H Query 9 - Product Type Profit Measure */
-- Invalid operation: function year(timestamp without time zone) does not exist;
SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM (SELECT N_NAME AS NATION, year(O_ORDERDATE) AS O_YEAR,
 L_EXTENDEDPRICE*(1-L_DISCOUNT)-PS_SUPPLYCOST*L_QUANTITY AS AMOUNT
 FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
 WHERE S_SUPPKEY = L_SUPPKEY AND PS_SUPPKEY= L_SUPPKEY AND PS_PARTKEY = L_PARTKEY AND
 P_PARTKEY= L_PARTKEY AND O_ORDERKEY = L_ORDERKEY AND S_NATIONKEY = N_NATIONKEY AND
 P_NAME LIKE '%%green%%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC

/* TPC_H Query 10 - Returned Item Reporting */
-- error on embedded select
WITH S AS (SELECT SUM(PS_SUPPLYCOST*PS_AVAILQTY) * 0.0001000000 AS PS_SUM
 FROM PARTSUPP, SUPPLIER, NATION
 WHERE PS_SUPPKEY = S_SUPPKEY AND S_NATIONKEY = N_NATIONKEY AND N_NAME = 'GERMANY')

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST*PS_AVAILQTY) AS SUM_VALUE
FROM PARTSUPP, SUPPLIER, NATION, S
WHERE PS_SUPPKEY = S_SUPPKEY AND S_NATIONKEY = N_NATIONKEY AND N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY, PS_SUPPLYCOST, PS_AVAILQTY, PS_SUM
HAVING SUM(PS_SUPPLYCOST*PS_AVAILQTY) > PS_SUM
ORDER BY SUM_VALUE DESC
SELECT L_SHIPMODE,
SUM(CASE WHEN O_ORDERPRIORITY = '1-URGENT' OR O_ORDERPRIORITY = '2-HIGH' THEN 1 ELSE 0 END) AS HIGH_LINE_COUNT,
SUM(CASE WHEN O_ORDERPRIORITY <> '1-URGENT' AND O_ORDERPRIORITY <> '2-HIGH' THEN 1 ELSE 0 END ) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY AND L_SHIPMODE IN ('MAIL','SHIP')
AND L_COMMITDATE < L_RECEIPTDATE AND L_SHIPDATE < L_COMMITDATE AND L_RECEIPTDATE >= DATE'1994-01-01'
AND L_RECEIPTDATE < DATE'1995-10-01' 
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE

/* TPC_H Query 11 - Important Stock Identification */
-- 7.79s / 0.77s
-- 7.40s / 5.05s
SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM (SELECT C_CUSTKEY, COUNT(O_ORDERKEY)
 FROM spectrum.CUSTOMER left outer join spectrum.ORDERS on C_CUSTKEY = O_CUSTKEY
 AND O_COMMENT not like '%%special%%requests%%'
 GROUP BY C_CUSTKEY) AS C_ORDERS (C_CUSTKEY, C_COUNT)
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC

/* TPC_H Query 12 - Shipping Modes and Order Priority */
-- 6.33s / 0.41s
-- 16.38s /16.38s
SELECT 100.00* SUM(CASE WHEN P_TYPE LIKE 'PROMO%%' THEN L_EXTENDEDPRICE*(1-L_DISCOUNT)
ELSE 0 END) / SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS PROMO_REVENUE
FROM spectrum.LINEITEM, spectrum.PART
WHERE L_PARTKEY = P_PARTKEY AND L_SHIPDATE >= DATE'1995-09-01' AND L_SHIPDATE < DATE'1995-10-01'

/* TPC_H Query 13 - Customer Distribution */
-- 0.77 / 0.75
-- 6.39s / 5.32s
SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM (SELECT C_CUSTKEY, COUNT(O_ORDERKEY)
 FROM spectrum.CUSTOMER left outer join spectrum.ORDERS on C_CUSTKEY = O_CUSTKEY
 AND O_COMMENT not like '%%special%%requests%%'
 GROUP BY C_CUSTKEY) AS C_ORDERS (C_CUSTKEY, C_COUNT)
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC
/* TPC_H Query 15 - Create View for Top Supplier Query

WITH V AS  (SELECT L_SUPPKEY AS SUPPLIER_NO, 
            SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS TOTAL_REVENUE FROM
            LINEITEM WHERE L_SHIPDATE >= DATE'1996-01-01' 
            AND L_SHIPDATE < DATE'1996-04-01' GROUP BY L_SUPPKEY),
M AS (SELECT MAX(TOTAL_REVENUE) AS MAX_REV FROM V)

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, V, M
WHERE S_SUPPKEY = SUPPLIER_NO AND TOTAL_REVENUE = MAX_REV
ORDER BY S_SUPPKEY

/* TPC_H Query 16 - Parts/Supplier Relationship */
-- 8.92s / 1.45s
-- 11.07s / 9.0s
SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM spectrum.PARTSUPP, spectrum.PART
WHERE P_PARTKEY = PS_PARTKEY AND P_BRAND <> 'Brand#45' AND P_TYPE NOT LIKE 'MEDIUM POLISHED%%'
AND P_SIZE IN (49, 14, 23, 45, 19, 3, 36, 9) AND PS_SUPPKEY NOT IN (SELECT S_SUPPKEY FROM spectrum.SUPPLIER
 WHERE S_COMMENT LIKE '%%Customer%%Complaints%%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE

/* TPC_H Query 17 - Small-Quantity-Order Revenue */
-- 7.79s / 0.54s-
-- 36.01s / 29.11s
WITH S AS (SELECT 0.2*AVG(L_QUANTITY) AS S_QTY FROM spectrum.LINEITEM, spectrum.PART WHERE L_PARTKEY = P_PARTKEY)
SELECT SUM(L_EXTENDEDPRICE)/7.0 AS AVG_YEARLY FROM spectrum.LINEITEM, spectrum.PART, S
WHERE P_PARTKEY = L_PARTKEY AND P_BRAND = 'Brand#23' AND P_CONTAINER = 'MED BOX'
AND L_QUANTITY < S_QTY

/* TPC_H Query 18 - Large Volume Customer */
-- 10.39s / 1.36s
-- 37.11s / 31.86s
WITH S AS (SELECT L_ORDERKEY AS L_KEY FROM spectrum.LINEITEM GROUP BY L_ORDERKEY, L_QUANTITY 
           HAVING SUM(L_QUANTITY) > 300)
SELECT C_NAME, C_CUSTKEY, O_ORDERKEY, O_ORDERDATE, O_TOTALPRICE, SUM(L_QUANTITY)
FROM spectrum.CUSTOMER, spectrum.ORDERS, spectrum.LINEITEM, S
WHERE O_ORDERKEY IN (L_KEY)  AND C_CUSTKEY = O_CUSTKEY AND O_ORDERKEY = L_ORDERKEY
GROUP BY C_NAME, C_CUSTKEY, O_ORDERKEY, O_ORDERDATE, O_TOTALPRICE
ORDER BY O_TOTALPRICE DESC, O_ORDERDATE

/* TPC_H Query 19 - Discounted Revenue */
-- 4.64s / 0.49s
-- 15.23s / 14.49s
SELECT SUM(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REVENUE
FROM spectrum.LINEITEM, spectrum.PART
WHERE (P_PARTKEY = L_PARTKEY AND P_BRAND = 'Brand#12' AND P_CONTAINER IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') AND L_QUANTITY >= 1 AND L_QUANTITY <= 1 + 10 AND P_SIZE BETWEEN 1 AND 5
AND L_SHIPMODE IN ('AIR', 'AIR REG') AND L_SHIPINSTRUCT = 'DELIVER IN PERSON')
OR (P_PARTKEY = L_PARTKEY AND P_BRAND ='Brand#23' AND P_CONTAINER IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') AND L_QUANTITY >=10 AND L_QUANTITY <=10 + 10 AND P_SIZE BETWEEN 1 AND 10 
AND L_SHIPMODE IN ('AIR', 'AIR REG') AND L_SHIPINSTRUCT = 'DELIVER IN PERSON') 
OR (P_PARTKEY = L_PARTKEY AND P_BRAND = 'Brand#34' AND P_CONTAINER IN ( 'LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') AND L_QUANTITY >=20 AND L_QUANTITY <= 20 + 10 AND P_SIZE BETWEEN 1 AND 15
AND L_SHIPMODE IN ('AIR', 'AIR REG') AND L_SHIPINSTRUCT = 'DELIVER IN PERSON')

/* TPC_H Query 20 - Potential Part Promotion */

WITH S AS (SELECT 0.5*sum(L_QUANTITY) 
			FROM LINEITEM 
			WHERE L_PARTKEY = PS_PARTKEY AND L_SUPPKEY = PS_SUPPKEY AND L_SHIPDATE >= DATE'1994-01-01' AND
  L_SHIPDATE < DATE'1995-01-01'),
 SELECT S_NAME, S_ADDRESS FROM SUPPLIER, NATION, S
WHERE S_SUPPKEY IN (SELECT PS_SUPPKEY FROM PARTSUPP
 WHERE PS_PARTKEY in (SELECT P_PARTKEY FROM PART WHERE P_NAME like 'forest%%') AND
 PS_AVAILQTY > (ssss) AND S_NATIONKEY = N_NATIONKEY AND N_NAME = 'CANADA'
ORDER BY S_NAME;
